CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  birthdate DATE NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  is_admin BOOLEAN NOT NULL DEFAULT 0,
  hashed_password VARCHAR(255) NOT NULL
);

CREATE TABLE recette (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  image VARCHAR(255) NOT NULL,
  ingredients VARCHAR(255) NOT NULL,
  serving INT NOT NULL,
  nutritional_values VARCHAR(255) NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY(user_id) REFERENCES user(id)
);

CREATE TABLE ingredient (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL
);

CREATE TABLE step (
  id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  recette_id INT UNSIGNED NOT NULL,
  text TEXT NOT NULL,
  FOREIGN KEY(recette_id) REFERENCES recette(id)
);